#This is the production workflow

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma db push && npm run start:prod"
    container_name: jubra-backend
    restart: always
    ports:
      - "3003:3001"
    environment:
      - DATABASE_URL=mysql://root:Sextape,123@mysql:3306/jubra_db
      - PORT=3001
      - SYSTEM_SECRET=MYAUTHSECRETISVERYSTRONG
      - MODE=Prod
      - REDIS_URL=redis://redis:6379
      - EMAIL_USER=
      - EMAIL_PASS=
    volumes:
      - /root/jubra/jubra-assets:/app/uploads
      - /root/jubra/assets:/app/src/assets
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - jubra-network

  redis:
    image: redis:7-alpine
    container_name: jubra-redis
    restart: always
    ports:
      - "6378:6379"
    networks:
      - jubra-network

  mysql:
    image: mysql:9.6.0
    container_name: jubra-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Sextape,123
      - MYSQL_DATABASE=jubra_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pSextape,123"]
    networks:
      - jubra-network

networks:
  jubra-network:
    name: "jubra-network"
    driver: bridge

volumes:
  mysql_data: